---
name: Build and Publish

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0'

jobs:
  build-and-publish:
    name: Publish container image
    runs-on: 'ubuntu-latest'
    permissions:
      contents: read
      packages: write
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Login to container registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          build-args: BUILDER_SRC=github.com/${{ github.repository }}
          push: true
          file: Dockerfile
          tags: ghcr.io/${{ github.repository }}:latest
