---
name: Build and Publish

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0'

jobs:
  build-and-publish:
    name: Publish container image
    runs-on: 'ubuntu-latest'
    permissions:
      contents: read
      packages: write
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Build container
        run: podman build -t ghcr.io/${{ github.repository }}:latest .

      - name: Login to container registry
        run: podman login -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }} ghcr.io

      - name: Push container to registry
        run: podman push ghcr.io/${{ github.repository }}:latest
