name: check

on: [pull_request]

jobs:
  check:
    name: Static code checks
    runs-on: ubuntu-latest
    permissions: {}

    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y make python3-pyflakes

      - name: Run pyflakes
        run: python3 -m pyflakes .
