---
name: Lint Code Base

on:
  push:
    branches: [main]
  pull_request:

jobs:
  lint:
    name: Lint Code Base
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Lint Code Base
        uses: ricardochaves/python-lint@v1.4.0
        with:
          python-root-list: "fedora-bot"
