# Poll for new releases in Fedora dist-git and schedule Koji builds and/or update Bodhi
name: "Fedora bot"

on:
  workflow_dispatch:
  schedule:
    - cron: '*/30 * * * *'

jobs:
  check:
    name: Check for new releases
    runs-on: ubuntu-latest

    container:
      image: ghcr.io/osbuild/fedora-bot:latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Check for new releases
        run: python3 fedora_bot.py --user imagebuilder-bot --password "${{ secrets.FEDORA_PASSWORD }}" --apikey "${{ secrets.FEDORA_APIKEY }}" --component osbuild:2 --component osbuild-composer:1 --component koji-osbuild:1 --component cockpit-composer:1
        shell: bash
        env:
          SLACK_WEBHOOK_URL: "${{ secrets.SLACK_WEBHOOK_URL }}"
