# Poll for new pull requests in Fedora dist-git auto-merge when green
name: "Fedora bot"

on:
  workflow_dispatch:
  schedule:
    # Every 30mins between 8AM and 3PM on Wednesdays
    - cron: '*/30 8-15 * * 3'

jobs:
  check:
    name: Check for new releases
    runs-on: ubuntu-latest

    container:
      image: ghcr.io/osbuild/fedora-bot:latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Check for new releases
        run: python3 fedora_bot.py --user imagebuilder-bot --password "${{ secrets.FEDORA_PASSWORD }}" --apikey "${{ secrets.FEDORA_APIKEY }}" --component osbuild:3 --component osbuild-composer:2 --component koji-osbuild:2 --component cockpit-composer:2 --component image-builder:2 --component cockpit-image-builder:2
        shell: bash
        env:
          SLACK_WEBHOOK_URL: "${{ secrets.SLACK_WEBHOOK_URL }}"
