# Poll for new releases in Fedora dist-git and schedule Koji builds and/or update Bodhi
name: "Reminder bot"

on:
  workflow_dispatch:
  schedule:
    - cron: '0 8 * * *'

jobs:
  weekly:
    name: Daily and weekly reminders
    runs-on: ubuntu-latest

    container:
      image: ghcr.io/osbuild/fedora-bot:latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Check for stale frontend PRs
        run: python3 reminder_bot.py -f
        shell: bash
        env:
          SLACK_WEBHOOK_URL: "${{ secrets.SLACK_WEBHOOK_URL }}"
          SLACK_NICKS_KEY: "${{ secrets.SLACK_NICKS_KEY }}"

